### PR TITLE
New 88-note rolls

### PR DESCRIPTION
**Pull request by broadwell**
This includes the changes from the [playback-fixes](https://github.com/sul-cidr/pianolatron/tree/playback-fixes) branch. Otherwise, the point is just to add the new rolls and also incorporate improvements to the MIDI of existing 88-note rolls (and to the hole data JSON of all playable rolls) that occurred as a consequence of changes made to the backend processing code to accommodate the new rolls.

A list of the new rolls, for reference:

DRUID | Title | Shelfmark
-- | -- | --
bv720gq2633 | Hiawatha's melody of love : waltz : key of E flat | sul:ars0178_b076_rythmodik_z106353
bx696fq3697 | Midsummer night's dream : op. 61. Nocturne | sul:ars0178_b095_universal_84307
cn498vz4750 | The  stars and stripes forever : march | sul:ars0178_b081_usregular_1812
ff220ct4404 | Symphony no. 3 in E flat, op. 55 : (Euroica). 3rd movement, Scherzo | sul:ars0178_b056_qrs_12517
fz108ts9393 | Tannhauser. "Oh thou sublime sweet evening star" | sul:ars0178_b076_solostyle_c3494
gp583km0927 | Rosen aus dem SuÌˆden : Walzer | sul:ars0178_b080_themodist_84632
kh288bx3828 | Impromptu, op. 142, no. 2, As = la beÌmol = Aâ™­ | sul:ars0209_b002_animatic_50385
ky144fd6229 | Symphony no. 3 in E flat, op. 55 : (Eroica). 2nd movement, Funeral march | sul:ars0178_b056_qrs_12507
nr538vy9112 | Sonata no. 12, F-dur = Fa majeur = F major. Allegro assai | sul:ars0209_b002_animatic_50319
ns724rz6542 | Sonate, C-dur = Ut majeur = C major : (KoÌˆch.-Verz. No. 330). Allegro moderato ; Andante cantabile | sul:ars0209_b002_animatic_50315
ny190nz5753 | Rhapsodie hongroise, no. 2 : key of E | sul:ars0178_b054_qrs_11091
ph633tr8751 | Sonato in A flat. Andante and variations | sul:ars0178_b056_qrs_12515
tn472jy2817 | Symphony no. 3 in E flat, op. 55 : (Eroica). 1st movement, Allegro con brio | sul:ars0178_b056_qrs_12506
wb438xf5756 | Symphonie, op. 92, no. 7. 2nd movement, Allegretto | sul:ars0178_b054_qrs_11070
wt920yb3768 | Mazurkas, op. 17. No.1, No.2, B flat ; E minor | sul:ars0178_b095_universal_84247
xn815zk7379 | Tannhauser. "Pilgrim's chorus" | sul:ars0178_b076_solostyle_c3484
xn861tf7013 | Edelweiss : op. 31: idylle | sul:ars0178_b095_universal_83847

### CODE REVIEW

**Review by simonwiles — APPROVED** [review]
LGTM :)

**Comment by moritztim** [comment]
@broadwell 
> changes made to the backend processing code to accommodate the new rolls.

Some of the roles Sebastian selected for the exhibition were not in the `catalog.json` when I forked. Do I need to port over some changes for these to work?
```
Themodist-Metrostyle [84632] Rosen aus dem süden: Walzer
Hupfeld [50385]              Impromptu, op. 142, no. 2, as = la bémol = a♭
US Regular [1812]            The Stars and stripes forever: march
```

**Comment by moritztim** [comment]
I just noticed that a couple of roll names have had whitespace changes, and then I saw that there are a lot of double spaces in general
image
`(?<=[^\s])  (?=[^\s])` Matches 86 times

**Comment by broadwell** [comment]
@moritztim 
> Some of the roles Sebastian selected for the exhibition were not in the `catalog.json` when I forked. Do I need to port over some changes for these to work?

Yeah, you can maybe just pull in the newest version of [catalog.json](https://github.com/sul-cidr/pianolatron/blob/develop/src/config/catalog.json) from the `develop` branch, or else cherry pick from https://github.com/sul-cidr/pianolatron/commit/57ccef8b37a659c7259e0f817429810dbf925ef7, if resyncing the entire fork causes way too many complications.

**Comment by broadwell** [comment]
> I just noticed that a couple of roll names have had whitespace changes, and then I saw that there are a lot of double spaces in general

Thanks for pointing this out. Unfortunately, the catalog data from which we derive the per-roll metadata (actually done in https://github.com/pianoroll/pianolatron-data/blob/main/build-pianolatron-files.py) remains a moving target, even for items that were accessioned years ago(!)
The appearance of these double-spaces actually necessitated some [emergency repairs](https://github.com/sul-cidr/pianolatron/commit/20d251ad0e11e4590c12dd4d17e8a11e63eb755a) to our search page for the full collection. It's unclear to us at which point we should rectify these issues with the source data; double spaces tend to be ignored in HTML rendering, so we're inclined to just pass them on for now.

**Comment by simonwiles** [comment]
The relevant "emergency repair" is probably 880128c, fwiw.  Fixing upstream would be great, but not something we can count on or wait around for, unfortunately.

**Comment by moritztim** [comment]
> @moritztim 
> 
> > Some of the roles Sebastian selected for the exhibition were not in the `catalog.json` when I forked. Do I need to port over some changes for these to work?
> 
> 
> 
> Yeah, you can maybe just pull in the newest version of [catalog.json](https://github.com/sul-cidr/pianolatron/blob/develop/src/config/catalog.json) from the `develop` branch, or else cherry pick from https://github.com/sul-cidr/pianolatron/commit/57ccef8b37a659c7259e0f817429810dbf925ef7, if resyncing the entire fork causes way too many complications.

Oh yeah, I already did that, I didn't even cherry pick, I just downloaded the newest version of `catalog.json` and `public/json` and added it to mine. This fork is now only a mirror of our internal repo, so I couldn't access upstream easily.
I was just wondering if there have been any relevant changes besides the json, since you mentioned changes to the data processing

**Comment by broadwell** [comment]
Ah, understood. There have been some minor changes recently to some of the red Welte-Mignon reproducing rolls and a few 88-note pianola rolls, which just affect the final notes of certain tracks in the MIDI and JSON files. The odds that they touch any of the rolls chosen for the exhibit are quite low, but to be safe, you could also download and incorporate the latest contents of `public/midi` and `public/note_midi` (or whichever version you use) from the `develop` branch.

**Pull request merged**
